# -*- coding: utf-8 -*-
"""analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCxu7yCWONKta-PRWHYsrLJYaPd0Xi_W
"""

from openai import OpenAI
import json
from prompt import build_k3_prompt
from rules import analyze_ppe, generate_caption
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

def k3_object_analyzer(objects):
    """
    objects: list[str]
    contoh:
    ["person", "helmet", "vest"]
    """

    # Rule-based analysis (fast & deterministic)
    risks = analyze_ppe(objects)
    rule_caption = generate_caption(objects)

    # LLM reasoning
    prompt = build_k3_prompt(objects)

    response = client.responses.create(
        model="gpt-4.1-mini",
        input=prompt
    )

    llm_output = response.output_text

    return {
        "detected_objects": objects,
        "rule_based_caption": rule_caption,
        "rule_based_risks": risks,
        "rule_based_risk_level": "LOW" if len(risks) == 0 else "HIGH",
        "llm_analysis": llm_output
    }


# === LOCAL TEST ===
if __name__ == "__main__":
    yolo_output = [
        "person",
        "vest",
        "helmet",
        "gloves",
        "boots",
        "goggles"
    ]

    result = k3_object_analyzer(yolo_output)
    print(result)