# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCxu7yCWONKta-PRWHYsrLJYaPd0Xi_W
"""

def build_k3_prompt(objects):
    return f"""
You are an AI assistant specialized in workplace safety (K3).

Detected objects:
{', '.join(objects)}

Tasks:
1. Generate a short scene caption.
2. Identify potential safety risks.
3. Assign a risk level: LOW, MEDIUM, or HIGH.
4. Provide safety recommendations.

Rules:
- Base analysis ONLY on detected objects.
- PPE violations (no_helmet, no_gloves, etc) MUST result in HIGH risk.
- Do not hallucinate objects.

Return the response strictly in JSON format:
{{
  "scene_caption": "",
  "potential_safety_risks": [],
  "risk_level": "",
  "safety_recommendations": []
}}
"""