# -*- coding: utf-8 -*-
"""rules.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCxu7yCWONKta-PRWHYsrLJYaPd0Xi_W
"""

def analyze_ppe(classes):
    risks = []

    if "person" in classes:
        if "no_helmet" in classes:
            risks.append("No helmet detected")
        if "no_gloves" in classes:
            risks.append("No gloves detected")
        if "no_boots" in classes:
            risks.append("No safety boots detected")
        if "no_goggle" in classes:
            risks.append("No safety goggles detected")

    return risks


def generate_caption(classes):
    if "person" in classes and "helmet" in classes:
        return "A person wearing proper safety equipment."
    elif "person" in classes:
        return "A person is detected with incomplete safety equipment."
    else:
        return "No person detected."