# -*- coding: utf-8 -*-
"""analyzer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCxu7yCWONKta-PRWHYsrLJYaPd0Xi_W
"""

from openai import OpenAI
import json
from prompt import build_k3_prompt
from rules import analyze_ppe, generate_caption
from dotenv import load_dotenv

load_dotenv()

client = OpenAI()

def k3_object_analyzer(objects):
    """
    objects: list[str]
    contoh:
    ["person", "helmet", "vest"]
    """

    # Rule-based analysis (fast & deterministic)
    risks = analyze_ppe(objects)
    rule_caption = generate_caption(objects)

    # Try LLM reasoning, but fallback to rule-based if API fails
    llm_output = None
    try:
        prompt = build_k3_prompt(objects)
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "user", "content": prompt}
            ]
        )
        llm_output = response.choices[0].message.content
    except Exception as e:
        print(f"OpenAI API Error: {e}")
        # Fallback to basic analysis without LLM
        llm_output = json.dumps({
            "scene_caption": rule_caption,
            "potential_safety_risks": risks,
            "risk_level": "LOW" if len(risks) == 0 else "HIGH",
            "safety_recommendations": [
                "Ensure all workers wear complete PPE",
                "Follow safety protocols",
                "Regular safety training required"
            ]
        })

    return {
        "detected_objects": objects,
        "rule_based_caption": rule_caption,
        "rule_based_risks": risks,
        "rule_based_risk_level": "LOW" if len(risks) == 0 else "HIGH",
        "llm_analysis": llm_output
    }


# === LOCAL TEST ===
if __name__ == "__main__":
    yolo_output = [
        "person",
        "vest",
        "helmet",
        "gloves",
        "boots",
        "goggles"
    ]

    result = k3_object_analyzer(yolo_output)
    print(result)